## TC 5033
### Word Embeddings

<br>

#### Activity 3b: Text Classification using RNNs and AG_NEWS dataset in PyTorch
<br>

- Objective:
    - Understand the basics of Recurrent Neural Networks (RNNs) and their application in text classification.
    - Learn how to handle a real-world text dataset, AG_NEWS, in PyTorch.
    - Gain hands-on experience in defining, training, and evaluating a text classification model in PyTorch.
    
<br>

- Instructions:
    - Data Preparation: Starter code will be provided that loads the AG_NEWS dataset and prepares it for training. Do not modify this part. However, you should be sure to understand it, and comment it, the use of markdown cells is suggested. 

    - Model Setup: A skeleton code for the RNN model class will be provided. Complete this class and use it to instantiate your model.

    - Implementing Accuracy Function: Write a function that takes model predictions and ground truth labels as input and returns the model's accuracy.

    - Training Function: Implement a function that performs training on the given model using the AG_NEWS dataset. Your model should achieve an accuracy of at least 80% to get full marks for this part.

    - Text Sampling: Write a function that takes a sample text as input and classifies it using your trained model.

    - Confusion Matrix: Implement a function to display the confusion matrix for your model on the test data.

    - Submission: Submit your completed Jupyter Notebook. Make sure to include a markdown cell at the beginning of the notebook that lists the names of all team members. Teams should consist of 3 to 4 members.
    
<br>

- Evaluation Criteria:

    - Correct setup of all the required libraries and modules (10%)
    - Code Quality (30%): Your code should be well-organized, clearly commented, and easy to follow. Use also markdown cells for clarity. Comments should be given for all the provided code, this will help you understand its functionality.
    
   - Functionality (60%): 
        - All the functions should execute without errors and provide the expected outputs.
        - RNN model class (20%)
        - Accuracy fucntion (10%)
        - Training function (10%)
        - Sampling function (10%)
        - Confucion matrix (10%)

        - The model should achieve at least an 80% accuracy on the AG_NEWS test set for full marks in this criterion.


Dataset

https://pytorch.org/text/stable/datasets.html#text-classification

https://paperswithcode.com/dataset/ag-news


# Integrantes del equipo:

*   Oscar Villa Cardenas - A01794052
*   Diego Alberto Olarte Mira - A01794028
*   Erick Alexei Cambray Servín - A01794243
*   Andres Javier Galindo Vargas - A01793927

### Import libraries

In [1]:
# conda install -c pytorch torchtext
# conda install -c pytorch torchdata
# conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch

In [2]:
# The following libraries are required for running the given code
# Please feel free to add any libraries you consider adecuate to complete the assingment.
import numpy as np
#PyTorch libraries
import torch
from torchtext.datasets import AG_NEWS
# Dataloader library
from torch.utils.data import DataLoader
from torch.utils.data.dataset import random_split
# Libraries to prepare the data
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator
from torchtext.data.functional import to_map_style_dataset
# neural layers
from torch import nn
from torch.nn import functional as F

# These libraries are suggested to plot confusion matrix
# you may use others
import scikitplot as skplt
import gc
from tqdm import tqdm
from sklearn.metrics import accuracy_score, confusion_matrix

In [3]:
# Use GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


### Get the train and the test datasets and dataloaders

Classes:

* 1 - World

* 2 - Sports

* 3 - Business

* 4 - Sci/Tech

We will convert them to:

* 0 - World

* 1 - Sports

* 2 - Business

* 3 - Sci/Tech

In [4]:
train_dataset, test_dataset = AG_NEWS()
train_dataset, test_dataset = to_map_style_dataset(train_dataset), to_map_style_dataset(test_dataset)

In [5]:
# Get the tokeniser
# tokeniser object
tokeniser = get_tokenizer('basic_english')

def yield_tokens(data):
    for _, text in data:
        yield tokeniser(text)

In [6]:
# Build the vocabulary
vocab = build_vocab_from_iterator(yield_tokens(train_dataset), specials=["<unk>"])
#set unknown token at position 0
vocab.set_default_index(vocab["<unk>"])

In [7]:
#test tokens
tokens = tokeniser('Welcome to TE3007')
print(tokens, vocab(tokens))

['welcome', 'to', 'te3007'] [3314, 4, 0]


In [8]:
NUM_TRAIN = int(len(train_dataset)*0.9)
NUM_VAL = len(train_dataset) - NUM_TRAIN

In [9]:
train_dataset, val_dataset = random_split(train_dataset, [NUM_TRAIN, NUM_VAL])

In [10]:
print(len(train_dataset), len(val_dataset), len(test_dataset))

108000 12000 7600


In [11]:
# function passed to the DataLoader to process a batch of data as indicated
max_words = 25
def collate_batch(batch):
    Y, X = list(zip(*batch))
    X = [vocab(tokeniser(text)) for text in X]
    X = [tokens+([0]* (max_words-len(tokens))) if len(tokens)<max_words else tokens[:max_words] for tokens in X] ## Bringing all samples to max_words length.

    return torch.tensor(X, dtype=torch.int32), torch.tensor(Y) - 1 ## We have deducted 1 from target names to get them in range [0,1,2,3] from [1,2,3,4]

In [12]:
labels =  ["World", "Sports", "Business", "Sci/Tech"]
max_tokens = 50
BATCH_SIZE = 256

In [13]:
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, collate_fn=collate_batch, shuffle = True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, collate_fn=collate_batch, shuffle = True)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, collate_fn=collate_batch, shuffle = True)

### Let us build our RNN model

In [14]:
EMBEDDING_SIZE = 50
NEURONS = 50
LAYERS = 1
#In the meantime we just say 4 classes
NUM_CLASSES = 4

In [15]:
class RNN_Model_1(nn.Module):
    def __init__(self, embed_size, hidden, layers, num_classes):
        super().__init__()
        self.embedding_layer = nn.Embedding(num_embeddings=len(vocab), 
                                            embedding_dim=embed_size)
        
        self.hidden = hidden
        self.layers = layers

        self.rnn = nn.RNN(input_size=embed_size, hidden_size=hidden, num_layers=layers, batch_first=True)
                        # You may use PyTorch nn.GRU(), nn.RNN(), or nn.LSTM()
        
        self.fc = nn.Linear(hidden, num_classes)
        
    def forward(self, x):
        embeddings = self.embedding_layer(x)
        output, hidden = self.rnn(embeddings, torch.randn(self.layers, len(x), self.hidden))
        return self.fc(output[:,-1])

In [16]:
loss_fn = nn.CrossEntropyLoss()

In [17]:
def accuracy(model, loader):
    with torch.no_grad():
        Y_shuffled, Y_preds, losses = [],[],[]
        for X, Y in val_loader:
            preds = model(X)
            loss = loss_fn(preds, Y)
            losses.append(loss.item())

            Y_shuffled.append(Y)
            Y_preds.append(preds.argmax(dim=-1))

        Y_shuffled = torch.cat(Y_shuffled)
        Y_preds = torch.cat(Y_preds)

        return accuracy_score(Y_shuffled.detach().numpy(), Y_preds.detach().numpy())

In [18]:
def train(model, optimiser, epochs=100):
    for i in range(1, epochs+1):
        losses = []
        for X, Y in tqdm(train_loader):
            Y_preds = model(X)
            
            loss = loss_fn(Y_preds, Y)
            losses.append(loss.item())

            optimiser.zero_grad()
            loss.backward()
            optimiser.step()

        print("Train Loss : {:.3f}".format(torch.tensor(losses).mean()))
        #CalcValLossAndAccuracy(model, loss_fn, val_loader)

In [19]:
epochs = 15
lr = 1e-3
# instantiate model
rnn_model = RNN_Model_1(EMBEDDING_SIZE, NEURONS, LAYERS, NUM_CLASSES)
optimiser = torch.optim.Adam(rnn_model.parameters(), lr=lr)


In [20]:
train(rnn_model, optimiser=optimiser,  epochs=epochs)

100%|██████████| 422/422 [00:18<00:00, 22.47it/s]


Train Loss : 1.103


100%|██████████| 422/422 [00:18<00:00, 23.25it/s]


Train Loss : 0.697


100%|██████████| 422/422 [00:19<00:00, 21.13it/s]


Train Loss : 0.526


100%|██████████| 422/422 [00:19<00:00, 22.14it/s]


Train Loss : 0.424


100%|██████████| 422/422 [00:19<00:00, 21.97it/s]


Train Loss : 0.363


100%|██████████| 422/422 [00:19<00:00, 22.19it/s]


Train Loss : 0.319


100%|██████████| 422/422 [00:18<00:00, 22.21it/s]


Train Loss : 0.288


100%|██████████| 422/422 [00:19<00:00, 21.93it/s]


Train Loss : 0.261


100%|██████████| 422/422 [00:19<00:00, 21.79it/s]


Train Loss : 0.238


100%|██████████| 422/422 [00:19<00:00, 21.50it/s]


Train Loss : 0.218


100%|██████████| 422/422 [00:19<00:00, 22.04it/s]


Train Loss : 0.202


100%|██████████| 422/422 [00:19<00:00, 22.03it/s]


Train Loss : 0.185


100%|██████████| 422/422 [00:19<00:00, 21.52it/s]


Train Loss : 0.168


100%|██████████| 422/422 [00:19<00:00, 21.95it/s]


Train Loss : 0.158


100%|██████████| 422/422 [00:19<00:00, 21.74it/s]

Train Loss : 0.146


In [21]:
print(f'{accuracy(rnn_model, test_loader):.4f}')

0.8722


In [22]:
def sample_text(model, loader):
    X_test_text, Y_test = [], []
    for Y, X in test_dataset:
        X_test_text.append(X)
        Y_test.append(Y-1)

    len(X_test_text)

    rng = np.random.RandomState(1)
    idx = rng.randint(1, len(X_test_text))
    X = [vocab(tokeniser(text)) for text in X_test_text[idx:idx+1]]
    X = [tokens+([0]* (max_words-len(tokens))) if len(tokens)<max_words else tokens[:max_words] for tokens in X] ## Bringing all samples to max_words length.
    preds = rnn_model(torch.tensor(X, dtype=torch.int32))
    preds = F.softmax(preds, dim=-1)

    print("Prediction : ", labels[preds.argmax()])
    print("Actual :     ", labels[Y_test[idx]])

In [23]:
sample_text(rnn_model, test_loader)

Prediction :  Business
Actual :      Business


In [24]:
# create confusion matrix
Y_shuffled, Y_preds = [], []
for X, Y in test_loader:
    preds = rnn_model(X)
    Y_preds.append(preds)
    Y_shuffled.append(Y)
gc.collect()
Y_preds, Y_shuffled = torch.cat(Y_preds), torch.cat(Y_shuffled)

Y_actual, Y_preds = Y_shuffled.detach().numpy(), F.softmax(Y_preds, dim=-1).argmax(dim=-1).detach().numpy()

print(confusion_matrix(Y_actual, Y_preds))

[[1667   60   77   96]
 [  54 1772   57   17]
 [  75   37 1563  225]
 [  85   19  152 1644]]
